# The URL the site will be built for
base_url = "/"
title = "ã©ãªéƒ¨å±‹"
description = "æ¯æ—¥ã‚¤ãƒ³ã‚¿ãƒ¼ãƒãƒƒãƒˆãŒæ—¥èª²"

default_language = "ja"


theme = "zerm"
compile_sass=true

taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "axar"

[extra]
author="donabe"
show_author = false
show_categories = true
show_tags = true
theme_color = "blue"
show_menu_items = 3
full_width = false
favicon = "/favicon.ico"
logo_text = "~/ã©ãªéƒ¨å±‹"

# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
    { url = "/profile/", name = "ğŸ‘¤ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«" },
    { url = "/contact/", name = "ğŸ“±Contact" },
    { url = "/blog/", name = "ğŸ“–ãƒ–ãƒ­ã‚°" },
    { url = "https://github.com/donabe8898", name = "GitHub", external = true },
    { url = "https://zenn.dev/donabe8898", name = "Zenn", external = true },
    { url = "/computer/", name = "ãƒã‚¤ã‚³ãƒ³ãƒ”ãƒ¥ãƒ¼ã‚¿" },
    { url = "https://sizu.me/donabe", name = "ã—ãšã‹ãªã‚¤ãƒ³ã‚¿ãƒ¼ãƒãƒƒãƒˆ", external = true },
]
menu_more = "show more"
read_more="ã‚Šãƒ¼ã©ãƒ¢ã‚¢"
read_other_posts = "ã‚‚ã£ã¨è¦‹ã‚‹"
enable_katex = true
center = true
disqus = { enabled=false, short_name="donalog" }
